### PR TITLE
There were some bugs in the displayed time on the wall

### PR DESCRIPTION
**Pull request by white-gecko**
I have fixed the date format and added a comment to the timezone setting (we should make this configurable)

### CODE REVIEW

**Comment by deiu** [comment]
Sorry, I didn't see the last commit.

**Comment by deiu** [comment]
Because I need to pass the timestamp as a moment() object. It's a bit flaky but it won't work otherwise. I'm still investigating it.

**Comment by white-gecko** [comment]
It works on my machine with only one moment().

**Comment by deiu** [comment]
Yeah, weird. I'll merge your last commits then I can push this change.

**Pull request merged**
